export AIRFLOW_IMAGE_URI="ebury-challenge-airflow:latest"
export EBURY_USER="ebury"
export EBURY_PASSWORD="ebury"
export EBURY_DATABASE_CONN="postgresql://ebury:ebury@ebury-data-warehouse:5432/prod"
export EBURY_POSTGRES_DB="prod"
